### ISSUE TITLE
chabok 1.5.0 && RN version 0.60

### ISSUE THREAD

**Issue by MehranTaheri** [chabok-io/chabok-client-rn#2]
in android/app/build.gradle add:
dependencies {
...
    implementation 'com.adpdigital.push:chabok-lib:3.1.0'
...
}
and in android/app/src/main/java/com/storyt/MainApplication.java add:
import com.adpdigital.push.config.Environment;

**Comment by farbod-s** [comment]
<div dir="rtl">
سلام
<br>
با اضافه کردن موارد فوق مشکل راه‌اندازی برطرف شد؟
</div>
