### ISSUE TITLE
مشکل در نصب اولیه چابک

### ISSUE THREAD

**Issue by mmdarzi** [chabok-io/chabok-client-rn#5]
<p dir="rtl">سلام. وقت بخیر</p>
<p dir="rtl">من نسخه 1.1.1 چابک رو از طریق لینک زیر قدم به قدم پیش رفتم و نصب کردم</p>
<p dir="rtl"><a href="https://doc.chabok.io/react-native-bridge/sdk-setup-old.html">https://doc.chabok.io/react-native-bridge/sdk-setup-old.html</a></p>
<p dir="rtl">توی نسخه اندروید موقعی که پروژه رو میخوام بیلد کنم با ارور زیر مواجه میشم:</p>
<pre><code>&gt; Task :app:compileDebugJavaWithJavac FAILED
G:\React Native\BlueApp\android\app\src\main\java\com\blueapp\MainApplication.java:65: error: cannot find symbol
        ChabokReactPackage.notificationOpened(message, notificationAction);
                          ^
  symbol:   method notificationOpened(ChabokNotification,ChabokNotificationAction)
  location: class ChabokReactPackage
1 error</code></pre><p dir="rtl">طبق آموزشی که داده شده باید قطعه کد زیر رو توی متد onCreate در فایل MainApplication.java قرار بدم. منم همین کارو کردم. ولی از همین یه تیکه کد داره ایراد میگیره. اینو که برمیدارم پروژه بیلد میشه</p>
<pre><code> AdpPushClient.get().addNotificationHandler(new NotificationHandler() {
      @Override
      public boolean notificationOpened(ChabokNotification message, ChabokNotificationAction notificationAction) {
        ChabokReactPackage.notificationOpened(message, notificationAction);
        return super.notificationOpened(message, notificationAction);
      }
    });</code></pre>

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">من نسخه 1.1.1 چابک رو از طریق لینک زیر قدم به قدم پیش رفتم و نصب کردم</p>
</blockquote>
<p dir="rtl">دلیل خاصی داره که از این نسخه استفاده می‌کنین؟ </p>
<p dir="rtl">پیشنهاد می‌کنیم حتما از نسخه ۲ کتابخانه ریکت‌نیتو چابک استفاده کنین. </p>
<p dir="rtl">مستندات راه‌اندازی نسخه ۲ کتابخانه ریکت‌نیتو چابک:</p>
<p dir="rtl"><a href="https://doc.chabok.io/react-native-bridge/sdk-setup.html#%DB%B1--%D9%86%D8%B5%D8%A8-%DA%A9%D8%AA%D8%A7%D8%A8%D8%AE%D8%A7%D9%86%D9%87">https://doc.chabok.io/react-native-bridge/sdk-setup.html#%DB%B1--%D9%86%D8%B5%D8%A8-%DA%A9%D8%AA%D8%A7%D8%A8%D8%AE%D8%A7%D9%86%D9%87</a></p>

**Comment by mmdarzi** [comment]
یکی از دوستانم مدت هاست داره از نسخه 1 استفاده میکنه و خیلی هم راضیه و میگه باگی نداره این نسخه

اتفاقا نسخه ی 2 رو هم نصب کردم. ولی بعد از نصب دیگه کلا پروژه بیلد نمیشه
با این ارور مواجه میشم
Execution failed for task ':app:generateDebugBuildConfig'.
> org.xml.sax.SAXParseException; systemId: file:/G:/React%20Native/BlueApp/android/app/src/main/AndroidManifest.xml; lineNumber: 5; columnNumber: 97; The prefix "tools" for attribute "tools:node" associated with an element type "uses-permission" is not bound.

اینو طبق آموزش خودتون گذاشته بودم توی فایل اندروید مانیفست. البته مشخص نکردبن کجای اون فایل باید قرار بدم ولی هرجاش باشه ارور میده.بعد که این قسمت رو از فایل اندروید مانیفست حذف میکنم پروژه بیلد میشه

ولی این بار با پیغام keeps stopping مواجه میشم و از اپلیکیشن میپره بیرون

لازم به ذکره که بنده از ری اکت نسخه 59.9 استفاده میکنم

**Comment by Husseinhj** [comment]
<blockquote dir="rtl">
<p dir="rtl">یکی از دوستانم مدت هاست داره از نسخه 1 استفاده میکنه و خیلی هم راضیه و میگه باگی نداره این نسخه</p>
</blockquote>
<p dir="rtl">باعث افتخارمون هست.</p>
<p dir="rtl">برای مشکلی در بالا اشاره کردید مربوط به import های پکیج چابک هست که در صورت اضافه کردن importهای چابک مشکل شما حل خواهد شد برای این موضوع می‌تونین نمونه کد ما رو مشاهد کنین:</p>
<p dir="rtl"><a href="https://github.com/chabok-io/chabok-starter-rn/blob/81c20a4b9b7e860fbb06dbc7f43e15351c343355/android/app/src/main/java/com/chabokstarterrnbridge/MainApplication.java#L3-L19">https://github.com/chabok-io/chabok-starter-rn/blob/81c20a4b9b7e860fbb06dbc7f43e15351c343355/android/app/src/main/java/com/chabokstarterrnbridge/MainApplication.java#L3-L19</a></p>
<blockquote dir="rtl">
<p dir="rtl">اتفاقا نسخه ی 2 رو هم نصب کردم. ولی بعد از نصب دیگه کلا پروژه بیلد نمیشه با این ارور مواجه میشم</p>
</blockquote>
<p dir="rtl">این موضوع به فایل AndroidManifest پروژه‌اتون هست که در این اissue در stackoverflow بهش اشاره شده</p>
<p dir="rtl"><a href="https://stackoverflow.com/questions/55334431/facing-below-error-toolsnode-associated-with-an-element-type-uses-permission">https://stackoverflow.com/questions/55334431/facing-below-error-toolsnode-associated-with-an-element-type-uses-permission</a></p>

**Comment by mmdarzi** [comment]
توی نسخه 1 که نصب کردم عینا نمونه فایلی رو لینک دادین کپی کردم تو پروژه.. منظورم MainApplication.java هست
ایمپورت های قبلی پروژه خودمو هم باز اضافه کردم بهش
مجدد به همون ارور قبلی خوردم

G:\React Native\BlueApp-chabok1\android\app\src\main\java\com\blueapp\MainApplication.java:98: error: cannot find symbol
          ChabokReactPackage.notificationOpened(message, notificationAction);
                            ^
  symbol:   method notificationOpened(ChabokNotification,ChabokNotificationAction)
  location: class ChabokReactPackage
Note: G:\React Native\BlueApp-chabok1\android\app\src\main\java\com\blueapp\MainApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

**Comment by Husseinhj** [comment]
<p dir="rtl">@mmdarzi 
آیا import زیر در این فایل وجود دارد؟</p>
<pre><code class="language-java">import com.adpdigital.push.rn.ChabokReactPackage;</code></pre>
<p dir="rtl">لطفا در صورت امکان و حفظ مسائل امنیتی کدهای این فایل رو برای ما ارسال کنین. </p>

**Comment by mmdarzi** [comment]
بله تمام import هارو عینا کپی کردم از لینکی که فرستادین

بله حتما. بفرمایید چه جوری بفرستم خدمت تون؟

**Comment by mmdarzi** [comment]
من یه دونه پروژه جدید ری اکت نسخه 59.9 نصب کردم. گفتم شاید چابک با ماژول هایی که روی پروژه م نصبه مشکل داره. ولی باز هم به همین ارور خوردم. الان شما یه تست بکنید ببینید میتونید روی نسخه 59 نصب کنید چابک رو یا نه؟

برای نصب از این لینک رفتم:
https://doc.chabok.io/react-native-bridge/sdk-setup-old.html

دستور نصب هم این شکلی وارد کردم :
npm install react-native-chabok@1.1.1 --save

**Comment by Husseinhj** [comment]
<p dir="rtl">پیرو تماس تلفنی که باهم داشتیم. مشکل شما به خاطر استفاده از importهای غیر مرتبط به چابک در فایل MainApplication.java بود که در مستندات به اون اشاره شده بود. پس از حذف این importها مشکل حل شد.</p>
